[project]
name = "portopt-en"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keyboard>=0.13.5",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scipy>=1.18.1",
    "tensorflow>=2.21.0",
    "tqdm>=4.70.1",
    "yfinance>=1.7.0",
]
